excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://JamesICT.github.io
title: Git
email: jamesict@gmail.com
author: James Burton
description: My awesome new site
paginate: 3
google_analytics: 